// ============================================
//  PRESET FOLDERS — all preset data lives here
// ============================================

const PRESET_FOLDERS = [
  {
    id: 'pastels',
    name: 'Pastels',
    presets: [
      {
        id: 'original',
        name: 'Original',
        brightness: 1.0,
        saturation: 1.0,
        tint: { r: 0, g: 0, b: 0 },
        fade: 0,
      },
      {
        id: 'blush',
        name: 'Blush',
        brightness: 1.08,
        saturation: 1.40,
        tint: { r: 30, g: 6, b: 18 },
        fade: 10,
        warmth: 6,
        splitTone: {
          highlightTint: { r: 26, g: 6, b: 20 },
          shadowTint: { r: 10, g: 2, b: 8 },
        },
      },
      {
        id: 'petal',
        name: 'Petal',
        brightness: 1.04,
        saturation: 1.05,
        tint: { r: 22, g: 8, b: 26 },
        fade: 10,
        warmth: 2,
        splitTone: {
          highlightTint: { r: 20, g: 6, b: 24 },
          shadowTint: { r: 8, g: 4, b: 10 },
        },
      },
      {
        id: 'lavender',
        name: 'Lavender',
        brightness: 1.04,
        saturation: 1.15,
        tint: { r: 18, g: 8, b: 26 },
        fade: 7,
        warmth: -2,
        splitTone: {
          highlightTint: { r: 16, g: 6, b: 28 },
          shadowTint: { r: 6, g: 2, b: 12 },
        },
      },
      {
        id: 'cotton-candy',
        name: 'Cotton Candy',
        brightness: 1.08,
        saturation: 1.25,
        tint: { r: 26, g: 6, b: 34 },
        fade: 7,
        warmth: 2,
        splitTone: {
          highlightTint: { r: 22, g: 4, b: 32 },
          shadowTint: { r: 8, g: 2, b: 14 },
        },
      },
      {
        id: 'mist',
        name: 'Mist',
        brightness: 1.06,
        saturation: 1.05,
        tint: { r: 4, g: 16, b: 26 },
        fade: 7,
        warmth: -4,
        splitTone: {
          highlightTint: { r: 4, g: 14, b: 24 },
          shadowTint: { r: 2, g: 6, b: 10 },
        },
      },
      {
        id: 'sky',
        name: 'Sky',
        brightness: 1.08,
        saturation: 1.25,
        tint: { r: 2, g: 16, b: 38 },
        fade: 6,
        warmth: -10,
        splitTone: {
          highlightTint: { r: 2, g: 14, b: 36 },
          shadowTint: { r: 0, g: 4, b: 16 },
        },
      },
      {
        id: 'cream',
        name: 'Cream',
        brightness: 1.10,
        saturation: 0.92,
        tint: { r: 30, g: 22, b: 10 },
        fade: 8,
        warmth: 12,
        contrast: 1.10,
        splitTone: {
          highlightTint: { r: 28, g: 20, b: 8 },
          shadowTint: { r: 12, g: 8, b: 2 },
        },
      },
    ]
  },
  {
    id: 'vibrant',
    name: 'Vibrant',
    presets: [
      {
        id: 'original',
        name: 'Original',
        brightness: 1.0,
        saturation: 1.0,
        tint: { r: 0, g: 0, b: 0 },
        fade: 0,
      },
      {
        id: 'rose',
        name: 'Rose',
        brightness: 1.02,
        saturation: 1.38,
        tint: { r: 20, g: 4, b: 8 },
        fade: 3,
        contrast: 1.15,
        warmth: 10,
        clarity: 0.30,
        vignette: 0.30,
        splitTone: {
          highlightTint: { r: 24, g: 4, b: 8 },
          shadowTint: { r: 14, g: 0, b: 4 },
        },
      },
      {
        id: 'peach',
        name: 'Peach',
        brightness: 1.05,
        saturation: 1.40,
        tint: { r: 24, g: 12, b: 2 },
        fade: 2,
        contrast: 1.18,
        warmth: 16,
        clarity: 0.28,
        vignette: 0.28,
        splitTone: {
          highlightTint: { r: 28, g: 14, b: 0 },
          shadowTint: { r: 16, g: 6, b: 0 },
        },
      },
      {
        id: 'violet',
        name: 'Violet',
        brightness: 1.03,
        saturation: 1.38,
        tint: { r: 14, g: 4, b: 20 },
        fade: 2,
        contrast: 1.18,
        warmth: -6,
        clarity: 0.32,
        vignette: 0.35,
        splitTone: {
          highlightTint: { r: 12, g: 2, b: 22 },
          shadowTint: { r: 8, g: 0, b: 14 },
        },
      },
      {
        id: 'electric-sky',
        name: 'Electric Sky',
        brightness: 1.06,
        saturation: 1.42,
        tint: { r: 0, g: 8, b: 38 },
        fade: 2,
        contrast: 1.18,
        warmth: -12,
        clarity: 0.35,
        vignette: 0.32,
        splitTone: {
          highlightTint: { r: 0, g: 10, b: 36 },
          shadowTint: { r: 0, g: 4, b: 20 },
        },
      },
      {
        id: 'jade',
        name: 'Jade',
        brightness: 1.03,
        saturation: 1.38,
        tint: { r: 2, g: 20, b: 8 },
        fade: 2,
        contrast: 1.18,
        warmth: -4,
        clarity: 0.30,
        vignette: 0.30,
        splitTone: {
          highlightTint: { r: 2, g: 22, b: 8 },
          shadowTint: { r: 0, g: 10, b: 4 },
        },
      },
      {
        id: 'fuchsia',
        name: 'Fuchsia',
        brightness: 1.04,
        saturation: 1.48,
        tint: { r: 26, g: 2, b: 20 },
        fade: 2,
        contrast: 1.22,
        warmth: 4,
        clarity: 0.35,
        vignette: 0.35,
        splitTone: {
          highlightTint: { r: 28, g: 2, b: 22 },
          shadowTint: { r: 14, g: 0, b: 12 },
        },
      },
    ]
  },
  {
    id: 'gradients',
    name: 'Gradients',
    presets: [
      {
        id: 'original',
        name: 'Original',
        brightness: 1.0,
        saturation: 1.0,
        tint: { r: 0, g: 0, b: 0 },
        fade: 0,
      },
      {
        id: 'golden-hour',
        name: 'Golden Hour',
        brightness: 1.08,
        saturation: 1.22,
        tint: { r: 14, g: 8, b: 0 },
        fade: 4,
        warmth: 10,
        clarity: 0.20,
        splitTone: {
          highlightTint: { r: 20, g: 12, b: 0 },
          shadowTint: { r: 10, g: 4, b: 0 },
        },
        gradient: {
          type: 'linear-top',
          stops: [
            { pos: 0.0, r: 255, g: 175, b: 60, a: 0.50 },
            { pos: 0.5, r: 255, g: 155, b: 40, a: 0.15 },
            { pos: 1.0, r: 0, g: 0, b: 0, a: 0.0 },
          ]
        }
      },
      {
        id: 'blue-hour',
        name: 'Blue Hour',
        brightness: 1.03,
        saturation: 1.08,
        tint: { r: 4, g: 10, b: 28 },
        fade: 5,
        warmth: -8,
        clarity: 0.18,
        splitTone: {
          highlightTint: { r: 4, g: 8, b: 24 },
          shadowTint: { r: 0, g: 4, b: 16 },
        },
        gradient: {
          type: 'linear-top',
          stops: [
            { pos: 0.0, r: 30, g: 50, b: 180, a: 0.50 },
            { pos: 0.5, r: 15, g: 35, b: 140, a: 0.15 },
            { pos: 1.0, r: 0, g: 0, b: 0, a: 0.0 },
          ]
        }
      },
      {
        id: 'rose-sky',
        name: 'Rose Sky',
        brightness: 1.06,
        saturation: 1.18,
        tint: { r: 24, g: 8, b: 14 },
        fade: 5,
        warmth: 6,
        clarity: 0.18,
        splitTone: {
          highlightTint: { r: 22, g: 6, b: 14 },
          shadowTint: { r: 10, g: 2, b: 8 },
        },
        gradient: {
          type: 'linear-top',
          stops: [
            { pos: 0.0, r: 230, g: 90, b: 140, a: 0.50 },
            { pos: 0.5, r: 210, g: 70, b: 120, a: 0.15 },
            { pos: 1.0, r: 0, g: 0, b: 0, a: 0.0 },
          ]
        }
      },
      {
        id: 'cotton-sky',
        name: 'Cotton Sky',
        brightness: 1.05,
        saturation: 1.12,
        tint: { r: 18, g: 8, b: 20 },
        fade: 5,
        warmth: 2,
        clarity: 0.15,
        splitTone: {
          highlightTint: { r: 20, g: 6, b: 22 },
          shadowTint: { r: 8, g: 2, b: 10 },
        },
        gradient: {
          type: 'linear-top',
          stops: [
            { pos: 0.0, r: 235, g: 120, b: 215, a: 0.58 },
            { pos: 0.4, r: 130, g: 150, b: 235, a: 0.30 },
            { pos: 0.7, r: 185, g: 115, b: 225, a: 0.14 },
            { pos: 1.0, r: 0, g: 0, b: 0, a: 0.0 },
          ]
        }
      },
      {
        id: 'lavender-sky',
        name: 'Lavender Sky',
        brightness: 1.04,
        saturation: 1.05,
        tint: { r: 10, g: 6, b: 18 },
        fade: 6,
        warmth: -4,
        clarity: 0.15,
        splitTone: {
          highlightTint: { r: 10, g: 6, b: 20 },
          shadowTint: { r: 4, g: 2, b: 10 },
        },
        gradient: {
          type: 'linear-top',
          stops: [
            { pos: 0.0, r: 160, g: 110, b: 210, a: 0.45 },
            { pos: 0.5, r: 140, g: 90, b: 190, a: 0.12 },
            { pos: 1.0, r: 0, g: 0, b: 0, a: 0.0 },
          ]
        }
      },
    ]
  },
  {
    id: 'cinema',
    name: 'Cinema',
    presets: [
      {
        id: 'original',
        name: 'Original',
        brightness: 1.0,
        saturation: 1.0,
        tint: { r: 0, g: 0, b: 0 },
        fade: 0,
      },
      {
        id: 'velvia',
        name: 'Matrix',
        brightness: 1.02,
        saturation: 1.30,
        tint: { r: 2, g: 16, b: 10 },
        fade: 2,
        contrast: 1.20,
        warmth: -8,
        grain: 4,
        clarity: 0.35,
        vignette: 0.40,
        splitTone: {
          highlightTint: { r: 4, g: 14, b: 8 },
          shadowTint: { r: 0, g: 8, b: 20 },
        },
      },
      {
        id: 'provia',
        name: 'Titanic',
        brightness: 1.03,
        saturation: 1.10,
        tint: { r: 4, g: 10, b: 18 },
        fade: 4,
        contrast: 1.10,
        warmth: -10,
        grain: 3,
        clarity: 0.25,
        vignette: 0.30,
        bloom: 0.12,
        splitTone: {
          highlightTint: { r: 8, g: 12, b: 20 },
          shadowTint: { r: 0, g: 4, b: 18 },
        },
      },
      {
        id: 'astia',
        name: 'Casablanca',
        brightness: 1.04,
        saturation: 0.85,
        tint: { r: 18, g: 12, b: 4 },
        fade: 12,
        contrast: 0.95,
        warmth: 12,
        grain: 6,
        clarity: 0.20,
        vignette: 0.45,
        splitTone: {
          highlightTint: { r: 22, g: 14, b: 0 },
          shadowTint: { r: 8, g: 4, b: 0 },
        },
      },
      {
        id: 'chrome',
        name: 'Blade',
        brightness: 0.96,
        saturation: 0.85,
        tint: { r: 2, g: 10, b: 16 },
        fade: 8,
        contrast: 1.20,
        warmth: -10,
        grain: 5,
        clarity: 0.40,
        vignette: 0.55,
        splitTone: {
          highlightTint: { r: 6, g: 4, b: 0 },
          shadowTint: { r: 0, g: 12, b: 22 },
        },
      },
      {
        id: 'eterna',
        name: 'Drive',
        brightness: 0.94,
        saturation: 0.80,
        tint: { r: 8, g: 8, b: 18 },
        fade: 14,
        contrast: 0.92,
        warmth: -6,
        grain: 5,
        clarity: 0.30,
        vignette: 0.40,
        bloom: 0.18,
        splitTone: {
          highlightTint: { r: 16, g: 8, b: 0 },
          shadowTint: { r: 0, g: 8, b: 24 },
        },
      },
    ]
  },
  {
    id: 'glow',
    name: 'Glow',
    presets: [
      {
        id: 'original',
        name: 'Original',
        brightness: 1.0,
        saturation: 1.0,
        tint: { r: 0, g: 0, b: 0 },
        fade: 0,
        contrast: 1.0,
      },
      {
        id: 'neon-nights',
        name: 'Neon',
        brightness: 1.05,
        saturation: 1.35,
        tint: { r: 12, g: 0, b: 20 },
        fade: 0,
        contrast: 1.25,
        warmth: -6,
        clarity: 0.25,
        vignette: 0.50,
        bloom: 0.20,
        splitTone: {
          highlightTint: { r: 16, g: 0, b: 24 },
          shadowTint: { r: 6, g: 0, b: 14 },
        },
      },
      {
        id: 'electric',
        name: 'Electric',
        brightness: 0.98,
        saturation: 1.30,
        tint: { r: 0, g: 4, b: 24 },
        fade: 0,
        contrast: 1.35,
        warmth: -12,
        clarity: 0.30,
        vignette: 0.55,
        bloom: 0.18,
        splitTone: {
          highlightTint: { r: 0, g: 6, b: 28 },
          shadowTint: { r: 0, g: 2, b: 16 },
        },
      },
      {
        id: 'ember',
        name: 'Ember',
        brightness: 0.95,
        saturation: 1.28,
        tint: { r: 24, g: 6, b: 0 },
        fade: 0,
        contrast: 1.30,
        warmth: 20,
        clarity: 0.28,
        vignette: 0.55,
        bloom: 0.22,
        splitTone: {
          highlightTint: { r: 28, g: 10, b: 0 },
          shadowTint: { r: 14, g: 2, b: 0 },
        },
      },
      {
        id: 'midnight',
        name: 'Midnight',
        brightness: 0.88,
        saturation: 1.18,
        tint: { r: 4, g: 4, b: 18 },
        fade: 0,
        contrast: 1.35,
        warmth: -10,
        clarity: 0.35,
        vignette: 0.65,
        bloom: 0.14,
        splitTone: {
          highlightTint: { r: 4, g: 4, b: 22 },
          shadowTint: { r: 2, g: 0, b: 12 },
        },
      },
      {
        id: 'haze',
        name: 'Haze',
        brightness: 1.02,
        saturation: 1.22,
        tint: { r: 14, g: 0, b: 16 },
        fade: 3,
        contrast: 1.15,
        warmth: -4,
        clarity: 0.20,
        vignette: 0.45,
        bloom: 0.16,
        splitTone: {
          highlightTint: { r: 16, g: 0, b: 18 },
          shadowTint: { r: 8, g: 0, b: 10 },
        },
      },
    ]
  },
  {
    id: 'retro',
    name: 'Retro',
    presets: [
      {
        id: 'original',
        name: 'Original',
        brightness: 1.0,
        saturation: 1.0,
        tint: { r: 0, g: 0, b: 0 },
        fade: 0,
      },
      {
        id: 'kodak-gold',
        name: 'Kodak Gold',
        brightness: 1.05,
        saturation: 0.92,
        tint: { r: 22, g: 14, b: 0 },
        fade: 18,
        contrast: 0.95,
        warmth: 14,
        grain: 18,
        splitTone: {
          highlightTint: { r: 24, g: 16, b: 0 },
          shadowTint: { r: 12, g: 6, b: 0 },
        },
      },
      {
        id: 'polaroid',
        name: 'Polaroid',
        brightness: 1.12,
        saturation: 0.85,
        tint: { r: 10, g: 12, b: 18 },
        fade: 22,
        contrast: 0.90,
        warmth: -4,
        grain: 12,
        splitTone: {
          highlightTint: { r: 12, g: 14, b: 20 },
          shadowTint: { r: 4, g: 4, b: 10 },
        },
      },
      {
        id: 'portra-800',
        name: 'Portra 800',
        brightness: 1.06,
        saturation: 0.92,
        tint: { r: 22, g: 10, b: 10 },
        fade: 14,
        contrast: 0.92,
        warmth: 10,
        grain: 24,
        bloom: 0.12,
        splitTone: {
          highlightTint: { r: 28, g: 12, b: 14 },
          shadowTint: { r: 12, g: 4, b: 4 },
        },
      },
      {
        id: 'cross',
        name: 'Cross',
        brightness: 1.06,
        saturation: 1.22,
        tint: { r: 8, g: 18, b: 4 },
        fade: 8,
        contrast: 1.20,
        warmth: -8,
        grain: 14,
        clarity: 0.20,
        splitTone: {
          highlightTint: { r: 6, g: 20, b: 4 },
          shadowTint: { r: 2, g: 10, b: 8 },
        },
      },
      {
        id: 'digicam',
        name: 'Digicam',
        brightness: 1.10,
        saturation: 1.28,
        tint: { r: 4, g: 6, b: 14 },
        fade: 4,
        contrast: 1.22,
        warmth: -6,
        grain: 8,
        clarity: 0.28,
        vignette: 0.25,
        splitTone: {
          highlightTint: { r: 4, g: 8, b: 16 },
          shadowTint: { r: 0, g: 2, b: 8 },
        },
      },
      {
        id: 'crt',
        name: 'CRT',
        brightness: 0.95,
        saturation: 1.18,
        tint: { r: 0, g: 14, b: 8 },
        fade: 6,
        contrast: 1.28,
        warmth: -10,
        grain: 6,
        clarity: 0.32,
        vignette: 0.35,
        splitTone: {
          highlightTint: { r: 0, g: 18, b: 10 },
          shadowTint: { r: 0, g: 8, b: 4 },
        },
      },
      {
        id: 'vhs',
        name: 'VHS',
        brightness: 1.02,
        saturation: 0.85,
        tint: { r: 14, g: 6, b: 18 },
        fade: 16,
        contrast: 0.88,
        warmth: 4,
        grain: 20,
        vignette: 0.30,
        splitTone: {
          highlightTint: { r: 16, g: 6, b: 20 },
          shadowTint: { r: 8, g: 2, b: 10 },
        },
      },
      {
        id: 'svga',
        name: 'SVGA',
        brightness: 1.08,
        saturation: 0.82,
        tint: { r: 4, g: 16, b: 4 },
        fade: 10,
        contrast: 1.12,
        warmth: -12,
        grain: 10,
        clarity: 0.25,
        vignette: 0.28,
        splitTone: {
          highlightTint: { r: 4, g: 18, b: 4 },
          shadowTint: { r: 0, g: 8, b: 0 },
        },
      },
    ]
  },
  {
    id: 'noir',
    name: 'Noir',
    presets: [
      {
        id: 'original',
        name: 'Original',
        brightness: 1.0,
        saturation: 1.0,
        tint: { r: 0, g: 0, b: 0 },
        fade: 0,
        contrast: 1.0,
      },
      {
        id: 'classic-bw',
        name: 'Classic',
        brightness: 1.25,
        saturation: 0.0,
        tint: { r: 0, g: 0, b: 0 },
        fade: 0,
        contrast: 1.0,
      },
      {
        id: 'soft-bw',
        name: 'Soft',
        brightness: 1.25,
        saturation: 0.0,
        tint: { r: 4, g: 4, b: 4 },
        fade: 12,
        contrast: 0.90,
      },
      {
        id: 'dramatic-bw',
        name: 'Dramatic',
        brightness: 1.10,
        saturation: 0.0,
        tint: { r: 0, g: 0, b: 0 },
        fade: 0,
        contrast: 1.25,
      },
    ]
  }
];
