// ============================================
//  PRESET FOLDERS — all preset data lives here
// ============================================

const PRESET_FOLDERS = [
  {
    id: 'pastels',
    name: 'Pastels',
    presets: [
      {
        id: 'original',
        name: 'Original',
        brightness: 1.0,
        saturation: 1.0,
        tint: { r: 0, g: 0, b: 0 },
        fade: 0,
      },
      {
        id: 'blush',
        name: 'Blush',
        brightness: 1.08,
        saturation: 1.35,
        tint: { r: 34, g: 6, b: 14 },
        fade: 10,
        warmth: 8,
      },
      {
        id: 'petal',
        name: 'Petal',
        brightness: 1.04,
        saturation: 0.95,
        tint: { r: 22, g: 8, b: 26 },
        fade: 11,
        warmth: 2,
      },
      {
        id: 'lavender',
        name: 'Lavender',
        brightness: 1.04,
        saturation: 1.10,
        tint: { r: 18, g: 8, b: 26 },
        fade: 7,
      },
      {
        id: 'cotton-candy',
        name: 'Cotton Candy',
        brightness: 1.08,
        saturation: 1.20,
        tint: { r: 30, g: 8, b: 28 },
        fade: 7,
        warmth: 6,
      },
      {
        id: 'mist',
        name: 'Mist',
        brightness: 1.06,
        saturation: 1.00,
        tint: { r: 4, g: 16, b: 26 },
        fade: 7,
      },
      {
        id: 'sky',
        name: 'Sky',
        brightness: 1.08,
        saturation: 1.20,
        tint: { r: 2, g: 16, b: 38 },
        fade: 6,
        warmth: -8,
      },
      {
        id: 'cream',
        name: 'Cream',
        brightness: 1.10,
        saturation: 0.90,
        tint: { r: 30, g: 22, b: 10 },
        fade: 8,
        warmth: 10,
        contrast: 1.10,
      },
    ]
  },
  {
    id: 'vibrant',
    name: 'Vibrant',
    presets: [
      {
        id: 'original',
        name: 'Original',
        brightness: 1.0,
        saturation: 1.0,
        tint: { r: 0, g: 0, b: 0 },
        fade: 0,
      },
      {
        id: 'rose',
        name: 'Rose',
        brightness: 1.02,
        saturation: 1.35,
        tint: { r: 20, g: 4, b: 8 },
        fade: 3,
        contrast: 1.15,
        warmth: 10,
      },
      {
        id: 'peach',
        name: 'Peach',
        brightness: 1.05,
        saturation: 1.38,
        tint: { r: 23, g: 11, b: 2 },
        fade: 2,
        contrast: 1.18,
        warmth: 15,
      },
      {
        id: 'violet',
        name: 'Violet',
        brightness: 1.03,
        saturation: 1.35,
        tint: { r: 14, g: 4, b: 20 },
        fade: 2,
        contrast: 1.15,
        warmth: -4,
      },
      {
        id: 'electric-sky',
        name: 'Electric Sky',
        brightness: 1.06,
        saturation: 1.40,
        tint: { r: 0, g: 8, b: 38 },
        fade: 2,
        contrast: 1.15,
        warmth: -10,
      },
      {
        id: 'jade',
        name: 'Jade',
        brightness: 1.03,
        saturation: 1.35,
        tint: { r: 2, g: 18, b: 8 },
        fade: 2,
        contrast: 1.15,
        warmth: -4,
      },
      {
        id: 'fuchsia',
        name: 'Fuchsia',
        brightness: 1.04,
        saturation: 1.45,
        tint: { r: 24, g: 2, b: 18 },
        fade: 2,
        contrast: 1.20,
        warmth: 4,
      },
    ]
  },
  {
    id: 'gradients',
    name: 'Gradients',
    presets: [
      {
        id: 'original',
        name: 'Original',
        brightness: 1.0,
        saturation: 1.0,
        tint: { r: 0, g: 0, b: 0 },
        fade: 0,
      },
      {
        id: 'golden-hour',
        name: 'Golden Hour',
        brightness: 1.08,
        saturation: 1.20,
        tint: { r: 14, g: 8, b: 0 },
        fade: 4,
        gradient: {
          type: 'linear-top',
          stops: [
            { pos: 0.0, r: 255, g: 175, b: 60, a: 0.50 },
            { pos: 0.5, r: 255, g: 155, b: 40, a: 0.15 },
            { pos: 1.0, r: 0, g: 0, b: 0, a: 0.0 },
          ]
        }
      },
      {
        id: 'blue-hour',
        name: 'Blue Hour',
        brightness: 1.03,
        saturation: 1.05,
        tint: { r: 4, g: 10, b: 28 },
        fade: 5,
        gradient: {
          type: 'linear-top',
          stops: [
            { pos: 0.0, r: 30, g: 50, b: 180, a: 0.50 },
            { pos: 0.5, r: 15, g: 35, b: 140, a: 0.15 },
            { pos: 1.0, r: 0, g: 0, b: 0, a: 0.0 },
          ]
        }
      },
      {
        id: 'rose-sky',
        name: 'Rose Sky',
        brightness: 1.06,
        saturation: 1.15,
        tint: { r: 24, g: 8, b: 14 },
        fade: 5,
        gradient: {
          type: 'linear-top',
          stops: [
            { pos: 0.0, r: 230, g: 90, b: 140, a: 0.50 },
            { pos: 0.5, r: 210, g: 70, b: 120, a: 0.15 },
            { pos: 1.0, r: 0, g: 0, b: 0, a: 0.0 },
          ]
        }
      },
    ]
  },
  {
    id: 'glow',
    name: 'Glow',
    presets: [
      {
        id: 'original',
        name: 'Original',
        brightness: 1.0,
        saturation: 1.0,
        tint: { r: 0, g: 0, b: 0 },
        fade: 0,
        contrast: 1.0,
      },
      {
        id: 'neon-nights',
        name: 'Neon',
        brightness: 1.05,
        saturation: 1.30,
        tint: { r: 12, g: 0, b: 20 },
        fade: 0,
        contrast: 1.25,
        warmth: -6,
      },
      {
        id: 'electric',
        name: 'Electric',
        brightness: 0.98,
        saturation: 1.25,
        tint: { r: 0, g: 4, b: 24 },
        fade: 0,
        contrast: 1.35,
        warmth: -10,
      },
      {
        id: 'ember',
        name: 'Ember',
        brightness: 0.95,
        saturation: 1.25,
        tint: { r: 22, g: 6, b: 0 },
        fade: 0,
        contrast: 1.30,
        warmth: 18,
      },
      {
        id: 'midnight',
        name: 'Midnight',
        brightness: 0.88,
        saturation: 1.15,
        tint: { r: 4, g: 4, b: 18 },
        fade: 0,
        contrast: 1.35,
        warmth: -8,
      },
      {
        id: 'haze',
        name: 'Haze',
        brightness: 1.02,
        saturation: 1.20,
        tint: { r: 14, g: 0, b: 16 },
        fade: 3,
        contrast: 1.15,
        warmth: -4,
      },
    ]
  },
  {
    id: 'noir',
    name: 'Noir',
    presets: [
      {
        id: 'original',
        name: 'Original',
        brightness: 1.0,
        saturation: 1.0,
        tint: { r: 0, g: 0, b: 0 },
        fade: 0,
        contrast: 1.0,
      },
      {
        id: 'classic-bw',
        name: 'Classic',
        brightness: 1.25,
        saturation: 0.0,
        tint: { r: 0, g: 0, b: 0 },
        fade: 0,
        contrast: 1.0,
      },
      {
        id: 'soft-bw',
        name: 'Soft',
        brightness: 1.25,
        saturation: 0.0,
        tint: { r: 4, g: 4, b: 4 },
        fade: 12,
        contrast: 0.90,
      },
      {
        id: 'dramatic-bw',
        name: 'Dramatic',
        brightness: 1.10,
        saturation: 0.0,
        tint: { r: 0, g: 0, b: 0 },
        fade: 0,
        contrast: 1.25,
      },
    ]
  }
];
